apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: phs41smoz-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: phs41smoz-nodejs 
  name: phs41smoz-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: phs41smoz-nodejs 
